[package]
name = "scraping-thpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
regex = "1.9.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }